// <auto-generated />
namespace EFLastLab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addpersonandhomerelation5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpersonandhomerelation5));
        
        string IMigrationMetadata.Id
        {
            get { return "201905041603254_addpersonandhomerelation5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
